# Generated by Django 4.1.2 on 2022-10-31 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deparment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numItem', models.IntegerField()),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DataBottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('studentID', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updateAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField()),
                ('score', models.FloatField()),
                ('status', models.IntegerField()),
                ('endAt', models.DateField(blank=True, null=True)),
                ('deparment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.deparment')),
            ],
        ),
    ]
