# Generated by Django 4.1.2 on 2022-11-01 15:17

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('score', '0002_rename_deparment_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEvaluate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantityStudent', models.IntegerField()),
                ('dataBottle', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=200)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
