# Generated by Django 4.1.2 on 2022-11-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_historyevaluate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databottle',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
